# project.yml
name: macspanso
options:
  bundleIdPrefix: com.macspanso
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"
packages:
  Yams:
    url: https://github.com/jpsim/Yams
    from: 5.0.6
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
targets:
  macspanso:
    type: application
    platform: macOS
    sources:
      - path: macspanso
    info:
      path: macspanso/App/Info.plist
      properties:
        LSUIElement: true
        CFBundleName: macspanso
        CFBundleDisplayName: macspanso
        CFBundleShortVersionString: "1.1.0"
        CFBundleVersion: "2"
        NSHumanReadableCopyright: "Copyright © 2026 Macspanso"
    dependencies:
      - package: Yams
    settings:
      base:
        DEVELOPMENT_TEAM: 88ZPCYS252
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
  macspansoTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: macspansoTests
    dependencies:
      - target: macspanso
      - package: Yams
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        GENERATE_INFOPLIST_FILE: YES
